workflows:
  not-flow-android:
    name: Not Flow Android
    max_build_duration: 60
    instance_type: linux

    environment:
      java: 17

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build Not Flow AAB
        script: |
          chmod +x ./gradlew
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/**/*.aab
